# Generated by Django 4.2 on 2023-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_currency_rate_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10,
                                      verbose_name='Курс валюты'),
        ),
    ]
